# Generated by Django 3.0.8 on 2020-07-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menucategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='show_in_menu',
            field=models.BooleanField(default=True),
        ),
    ]
