# Generated by Django 3.1.7 on 2021-03-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menucategory_show_in_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='variations_display_style',
            field=models.IntegerField(choices=[(1, 'Mini card'), (2, 'List')], default=1),
        ),
    ]
