# Generated by Django 3.1.7 on 2021-03-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_menu_variations_display_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='Dark Mode'),
        ),
    ]
