# Generated by Django 3.0.7 on 2020-07-01 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20200630_1511'),
        ('restaurants', '0003_restaurantintegrations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('slug', models.UUIDField(editable=False, unique=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('on_hold', 'Aguardando'), ('shipped', 'Enviado'), ('complete', 'Concluido'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant', verbose_name='restaurante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('unity_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor unitário')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Variation')),
            ],
        ),
    ]
