# Generated by Django 3.0.7 on 2020-06-30 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'variation')},
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='restaurant',
        ),
    ]
