# Generated by Django 3.0.7 on 2020-06-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200629_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Variação'),
        ),
    ]
