# Generated by Django 3.1 on 2020-10-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200630_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ordem'),
        ),
    ]
