# Generated by Django 3.1 on 2020-10-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
