# Generated by Django 3.1.7 on 2021-03-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201001_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Variação'),
        ),
    ]
