# Generated by Django 3.1.7 on 2021-03-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210322_1504'),
        ('products', '0007_auto_20210322_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
