# Generated by Django 3.1.7 on 2021-03-26 04:18

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
