# Generated by Django 4.0.4 on 2022-05-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210611_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariation',
            options={'ordering': ('product', 'price', 'variation')},
        ),
    ]
